### ISSUE TITLE
ImportError: cannot import name 'DINOv2' from 'autodistill_dinov2'

### ISSUE THREAD

**Issue by rainbowpuffpuff** [autodistill/autodistill-dinov2#3]
the (/usr/local/lib/python3.10/dist-packages/autodistill_dinov2/__init__.py) file is empty currently so I cannot import the distilled DINOv2 yet 
(I noticed on the site that it's work in progress so I guess it is to be expected for now)

**Comment by capjamesg** [comment]
@rainbowpuffpuff Thank you for reporting! We have just launched classification support. We have [written a tutorial](https://blog.roboflow.com/train-classification-model-no-labeling/) that explains how this works with CLIP as an example base model, but you can substitute out CLIP for DINOv2. Note: DINOv2 has an additional `train()` call, outlined in the README, because you need to train a linear classifier (i.e. SVM, which we use in `autodistill_dinov2`) on the embeddings before using them.

**Comment by capjamesg** [comment]
The `__init__.py` file now has the requisite imports so I am going to close this Issue. If you need more assistance, let me know!
